### PR TITLE
fix(web): add a "reorg" label to reorged slots/blocks search results

### LINKED ISSUE #406: fix(web): add a "reorg" label to reorged slots/blocks search results
Currently, when searching for blocks that have a reorganized version in the search bar, the following is displayed in the search results:

image

We should add a badge labeled ‘Reorged’ next to the block number to indicate that it is a reorganized block. When clicked, the badge should redirect to the reorganized block, not the canonical one, by navigating to `/block/[reorged_block_hash]`

### PR DESCRIPTION
**Pull request by luis-herasme**
### Checklist

- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Adds a `reorg` label to reorged slots/blocks search results

### Related Issue
Closes #406

### Screenshots
Before:
image

After:
image
image

### CODE REVIEW

**Review by xFJA — APPROVED** [review]

File: apps/web/src/components/Badges/Badge.tsx
Comment (PJColombo) [inline apps/web/src/components/Badges/Badge.tsx:1]: wdyt about using an optional variant instead of creating a none variant to explicitly represent the absence of a style value?

File: .changeset/strong-masks-remain.md [hunk 1]
```diff
@@ -0,0 +1,5 @@
+---
+"@blobscan/web": patch
+---
+
+A new label "reorg" has been added to the reorged slots/blocks search results
```
Comment (PJColombo) [inline .changeset/strong-masks-remain.md:5]:
```suggestion
Added a new label "reorg" to the reorged slots/blocks search results
```

File: apps/web/src/components/SearchInput/SearchResults.tsx [hunk 2]
```diff
@@ -46,25 +47,31 @@ function getCategoryInfo(type: SearchCategory): CategoryInfo | undefined {
...
-                {label}
+                {categoryLabel}
               </div>
             )}
-            {id}
+            {label}
           </span>
+          {reorg && (
+            <Badge variant="primary" className="text-xs">
+              reorg
```
Comment (PJColombo) [inline apps/web/src/components/SearchInput/SearchResults.tsx:72]:
```suggestion
              Reorg
```

**Review by PJColombo — CHANGES_REQUESTED** [review]
Nice work.

Left a few comments

File: apps/web/src/components/Badges/Badge.tsx
Comment (luis-herasme) [reply apps/web/src/components/Badges/Badge.tsx:1]: [f965994](https://github.com/Blobscan/blobscan/pull/582/commits/f96599484da78f4a233f8b6af8d7609399cc0887)

**Review by PJColombo — CHANGES_REQUESTED** [review]
Can we resolve the type-check problem? The GitHub actions job is throwing an error

Feel free to merge this once resolved.

**Review by PJColombo — APPROVED** [review]
I’ve pushed a commit to fix some search unit tests. All jobs are now passing, so feel free to merge it.
